### ISSUE TITLE
[Feature]: Search User Details by Aadhar Number

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/database#10]
### So, what is it about?

1. The admin can search for a user by entering their Aadhar number.
2. If the user is found, all details associated with the Aadhar number will be displayed.
3. If the user is not found, an error message indicating "Not found" will be displayed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
@MishraSomesh001 Kindly assign me this issue

**Comment by MishraSomesh001** [comment]
## Assigned
@xTwo56 you have to submit at least one pr before 1.04.24,11:59pm.
