### ISSUE TITLE
[Enhancement]: Input roll number and batch number in add person function

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/database#4]
### So, what is it about?

1. Modify the addPerson function to accept parameters for roll number and batch number along with other details.
2. Update the struct to include roll number and batch number fields.
3. Modify the storage structure to accommodate roll number and batch number.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
@MishraSomesh001  kindly assign me this issue

**Comment by MishraSomesh001** [comment]
## Assigned 
@xTwo56 you have to submit a pr before 31-03-24, 11:59pm .
