### ISSUE TITLE
Enhancement: Instead of mapping with unit=>Details map it with address=>Details

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/database#5]
### So, what is it about?

1. Change the mapping from unit to address in the storage structure.
2. Ensure that the key for each person's details is their address.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
@MishraSomesh001  kindly assign me this issue

**Comment by MishraSomesh001** [comment]
## Assigned
@xTwo56 you have to submit a pr before 31-03-24, 11:59pm .
