### ISSUE TITLE
Enhancement: One user can input his details only once

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/database#6]
### So, what is it about?

Add a modifier in the addPerson function to ensure that the user has not already added their details.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shreyanshi210205** [comment]
@MishraSomesh001 please assign this task to me

**Comment by MishraSomesh001** [comment]
## Assigned
@Shreyanshi210205 you have to submit a pr before 31-03-24, 11:59pm
