### ISSUE TITLE
[Feature]: A user can update the details

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/database#7]
### So, what is it about?

1. Implement a function that allows users to update their details.
2. This function should take the user's updated details as parameters.
3. Check if the user has already added their details before allowing an update.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
@MishraSomesh001  Kindly assign me this issue

**Comment by MishraSomesh001** [comment]
## Assigned
@xTwo56 you have to submit a pr before 1-04-24, 11:59pm.
As you have other issues as well.
