### ISSUE TITLE
[Feature]: A user can view his details

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/database#8]
### So, what is it about?

1. Implement a function that allows users to view their own details.
2. Ensure that the function can only be called by the user whose details are being requested.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
@MishraSomesh001  kindly assign me this issue

**Comment by MishraSomesh001** [comment]
## Assigned
@xTwo56 you have to submit a pr before 01-04-24, 11:59pm.
As you have other issues as well.
