### ISSUE TITLE
[Feature]: Set Admin

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/database#9]
### So, what is it about?

1) Create a function set_admin() that sets a particular address as admin .
2) This set_admin() function can only be called only once.
3) Create a change admin function which can only be accessed by the current admin which takes another another as an input.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shreyanshi210205** [comment]
@MishraSomesh001 kindly assign this task to me.

**Comment by MishraSomesh001** [comment]
## Assigned
@Shreyanshi210205  you have to submit a pr before 01-04-24, 11:59pm.
As you have other issues as well.
